spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/vistalhoteldbs
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.data.mongodb.uri=mongodb+srv://mongobasic:mongo123@cluster0.pro5bts.mongodb.net/vistalhoteldbs?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=vistalhoteldbs

# K?t n?i MongoDB
spring.sql.init.mode=always
spring.sql.init.platform=mariadb

# Hibernate/JPA config
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

